I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/script.rpy", line 40, in script call
    call UIreturn
  File "game/scripts/script.rpy", line 40, in script call
    call UIreturn
ScriptError: could not find label 'UIreturn'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/script.rpy", line 40, in script call
    call UIreturn
  File "renpy/ast.py", line 1490, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/scripts/script.rpy", line 40, in script call
    call UIreturn
  File "renpy/script.py", line 918, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'UIreturn'.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Projeto Teste 1.0
Sun Jun 26 13:45:57 2022
